name: Run Tests

on: push

jobs:
  test:
    strategy:
      matrix:
        solr_version: [8, 10]
    name: test-solr-${{ matrix.solr_version }}
    runs-on: ubuntu-latest

    env:
      SOLR_USER: solr
      SOLR_PASSWORD: SolrRocks

    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        run: cat env.* > .env

      - name: Set version vars
        id: vars
        run: |
          if [ "${{ matrix.solr_version }}" = "8" ]; then
            echo "SOLR_PORT=6781" >> $GITHUB_OUTPUT
            echo "SOLR_SERVICE=solr" >> $GITHUB_OUTPUT
          else
            echo "SOLR_PORT=6783" >> $GITHUB_OUTPUT
            echo "SOLR_SERVICE=solr10" >> $GITHUB_OUTPUT
          fi

      - name: build image
        run: docker compose build ${{ steps.vars.outputs.SOLR_SERVICE }}

      - name: start container
        run: docker compose up -d ${{ steps.vars.outputs.SOLR_SERVICE }}

      - name: docker compose ps
        run: docker compose ps

      - name: wait for solr
        run: docker compose wait ${{ steps.vars.outputs.SOLR_SERVICE }}

      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: run tests
        run: bundle exec rspec
        env:
          SOLR_URL: http://localhost:${{ steps.vars.outputs.SOLR_PORT }}/
          GHA_TEST: "true"
